FROM ubuntu:24.04

ARG DEBIAN_FRONTEND=noninteractive

ARG EXIM_IMAP__CONF__CORE_DEST
ARG EXIM_IMAP__CONF__CORE_SOURCE
ARG EXIM_IMAP__CONF__OVERRIDES_DEST
ARG EXIM_IMAP__CONF__OVERRIDES_SOURCE
ARG EXIM_IMAP__DOCKERFILE__AUTHOR
ARG EXIM_IMAP__USER__ADMIN_DIR
ARG EXIM_IMAP__USER__ADMIN_GRP
ARG EXIM_IMAP__USER__ADMIN_NAME
ARG EXIM_IMAP__USER__ADMIN_SHELL
ARG EXIM_IMAP__USER__GRP
ARG EXIM_IMAP__USER__STD_DIR
ARG EXIM_IMAP__USER__STD_GRP
ARG EXIM_IMAP__USER__STD_NAME
ARG EXIM_IMAP__USER__STD_PASS
ARG EXIM_IMAP__USER__STD_SHELL
ARG EXIM_IMAP__USER__SYS_DIR
ARG EXIM_IMAP__USER__SYS_GRP
ARG EXIM_IMAP__USER__SYS_NAME
ARG EXIM_IMAP__USER__SYS_SHELL

LABEL authors=${EXIM_IMAP__DOCKERFILE__AUTHOR}

RUN apt update -y \
	&& apt install \
		dovecot-core \
		dovecot-imapd \
		dovecot-mysql \
		dovecot-pop3d \
		libsasl2-modules \
		sasl2-bin -y \
	&& apt clean	-y \
	&& groupadd ${EXIM_IMAP__USER__GRP} -f \
	&& useradd -m \
		-d ${EXIM_IMAP__USER__ADMIN_DIR} \
		-g ${EXIM_IMAP__USER__ADMIN_GRP} \
		-s ${EXIM_IMAP__USER__ADMIN_SHELL} \
		${EXIM_IMAP__USER__ADMIN_NAME} \
	&& useradd -m \
		-d ${EXIM_IMAP__USER__SYS_DIR} \
		-g ${EXIM_IMAP__USER__SYS_GRP} \
		-s ${EXIM_IMAP__USER__SYS_SHELL} \
		${EXIM_IMAP__USER__SYS_NAME} \
	&& useradd -m  \
		-d ${EXIM_IMAP__USER__STD_DIR} \
		-g ${EXIM_IMAP__USER__STD_GRP} \
		-s ${EXIM_IMAP__USER__STD_SHELL} \
		${EXIM_IMAP__USER__STD_NAME} \
	&& echo "${EXIM_IMAP__USER__STD_NAME}:${EXIM_IMAP__USER__STD_PASS}" | chpasswd

COPY ${EXIM_IMAP__CONF__CORE_SOURCE} ${EXIM_IMAP__CONF__CORE_DEST}
COPY ${EXIM_IMAP__CONF__OVERRIDES_SOURCE} ${EXIM_IMAP__CONF__OVERRIDES_DEST}

ENTRYPOINT [ "/usr/sbin/dovecot", "-F" ]
